
#Format:
#[[trees]]
#id = "sparkling"
#color = [r,g,b]
#
[[trees]]
id = "core_t1"
color = [254, 0xf7, 0x80]
[[trees]]
id = "core_t2"
color = [0x1f, 0x1f, 239]
[[trees]]
id = "core_t3"
color = [0x25, 0x25, 0x25]

[[trees]]
id = "coal"
color = [5, 5, 5]
[[trees]]
id = "iron"
color = [0xcf, 162, 0x88]
[[trees]]
id = "copper"
color = [205, 96, 57]
[[trees]]
id = "gold"
color = [0xff, 0xd0, 0x00]
[[trees]]
id = "redstone"
color = [222, 0, 26]
[[trees]]
id = "emerald"
color = [0x0, 0xf8, 0x81]
[[trees]]
id = "lapis"
color = [0x3d, 0x6d, 224]
[[trees]]
id = "diamond"
color = [0x46, 0xff, 0xf2]
[[trees]]
id = "quartz"
color = [255, 255, 255]
[[trees]]
id = "ancient"
color = [90, 43, 31]
[[trees]]
id = "clay"
color = [0xcf, 0xd2, 0xd7]
[[trees]]
id = "sand"
color = [233, 240, 178]
[[trees]]
id = "stone"
color = [0xb9, 0xb9, 0xb9]
[[trees]]
id = "gravel"
color = [0xa0, 0xa0, 0xa0]
[[trees]]
id = "glowstone"
color = [186, 144, 36]
[[trees]]
id = "amethyst"
color = [138, 89, 229]

[[trees]]
id = "desh"
color = [183, 82, 24]
[[trees]]
id = "ice_shard"
color = [192, 204, 251]
[[trees]]
id = "ostrum"
color = [118, 58, 73]
[[trees]]
id = "calorite"
color = [182, 41, 59]
[[trees]]
id = "demonite"
color = [80, 255, 227]
[[trees]]
id = "zinc"
color = [0xdb, 0xf3, 0xdf]
[[trees]]
id = "draconium"
color = [146, 6, 251]
[[trees]]
id = "aluminium"
color = [224, 228, 229]
[[trees]]
id = "uranium"
color = [0x92, 174, 0x77]
[[trees]]
id = "osmium"
color = [153, 188, 252]
[[trees]]
id = "fluorite"
color = [0xf5, 0xfd, 0xf9]
[[trees]]
id = "uraninite"
color = [21, 159, 58]
[[trees]]
id = "dimensional_shard"
color = [22, 227, 221]
[[trees]]
id = "apatite"
color = [27, 190, 237]
[[trees]]
id = "cinnabar"
color = [155, 26, 36]
[[trees]]
id = "niter"
color = [236, 0xca, 206]
[[trees]]
id = "tin"
color = [0x00, 0x75, 0xa8]
[[trees]]
id = "lead"
color = [79, 79, 171]
[[trees]]
id = "silver"
color = [83, 174, 200]
[[trees]]
id = "nickel"
color = [215, 182, 97]
[[trees]]
id = "ruby"
color = [181, 11, 40]
[[trees]]
id = "sapphire"
color = [21, 105, 254]
[[trees]]
id = "cobalt"
color = [0x48, 0x7d, 0xff]
[[trees]]
id = "juperium"
color = [35, 160, 236]
[[trees]]
id = "saturlyte"
color = [89, 5, 171]
[[trees]]
id = "neptunium"
color = [55, 42, 195]
[[trees]]
id = "radium"
color = [109, 255, 132]
[[trees]]
id = "plutonium"
color = [244, 244, 39]
[[trees]]
id = "electrolyte"
color = [9, 0, 191]
[[trees]]
id = "hellforged_parts"
color = [113, 238, 204]
